# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wardgate < Formula
  desc "API gateway for AI agents - conclave executor"
  homepage "https://github.com/wardgate/wardgate"
  version "0.15.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.15.0/wardgate-exec_0.15.0_darwin_amd64.tar.gz"
      sha256 "f6655604d95d8d2ea68f8a619c3bb04d492db96f39f625d865acfa7fc296305c"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.15.0/wardgate-exec_0.15.0_darwin_arm64.tar.gz"
      sha256 "5545c073de2c5b4657fa6ee6f8920b27a5c929264f872550d7893fedfe0cb10a"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.15.0/wardgate-exec_0.15.0_linux_amd64.tar.gz"
      sha256 "d60f8534ca07f42c2104899e9816f2635db94cc164505cddfe3b930b2366cc97"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.15.0/wardgate-exec_0.15.0_linux_arm64.tar.gz"
      sha256 "bfa049a32f8f7b724fe7deb5f4b3872e3051bd98c68a6d3358c5df785bf9fd36"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end
end
