# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WardgateCli < Formula
  desc "API gateway for AI agents - CLI client"
  homepage "https://github.com/wardgate/wardgate"
  version "0.18.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-cli_0.18.0_darwin_amd64.tar.gz"
      sha256 "932d388794a54e9d55c02ae5ae63197332c73702b90bc42e84373d7a8dbec037"

      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-cli_0.18.0_darwin_arm64.tar.gz"
      sha256 "6406f0a374761f073e415d340f61fd52f9c8a6a8a82b0d3790a21034cb1138db"

      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-cli_0.18.0_linux_amd64.tar.gz"
      sha256 "f704e098068aa1cd6f4dd40da3842094182af215d33e98a37ef778a1d72347fa"
      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-cli_0.18.0_linux_arm64.tar.gz"
      sha256 "765e68d4fe8872e2593684479b1b67503950fff4b962365422f6e3cb85c6b2af"
      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
  end
end
