# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wardgate < Formula
  desc "API gateway for AI agents - server"
  homepage "https://github.com/wardgate/wardgate"
  version "0.18.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate_0.18.0_darwin_amd64.tar.gz"
      sha256 "631421af38a4a1d66ee820c1d98e3c530ddda3e36335c868f6e4f2a3f9ac8a6d"

      define_method(:install) do
        bin.install "wardgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate_0.18.0_darwin_arm64.tar.gz"
      sha256 "3c63aeb397f12c167585574a6ed92d7a04386db1287e3f92865d9e0a1f896b57"

      define_method(:install) do
        bin.install "wardgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate_0.18.0_linux_amd64.tar.gz"
      sha256 "709e6e5e00d21dac4c62177553a28b9474697da53e9f7ebfd475503902de2273"
      define_method(:install) do
        bin.install "wardgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate_0.18.0_linux_arm64.tar.gz"
      sha256 "e127471228c42545b4696e884b2267c8b466fdb3ff4562331dc0762545753dd8"
      define_method(:install) do
        bin.install "wardgate"
      end
    end
  end
end
