# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WardgateExec < Formula
  desc "API gateway for AI agents - conclave executor"
  homepage "https://github.com/wardgate/wardgate"
  version "0.17.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-exec_0.17.1_darwin_amd64.tar.gz"
      sha256 "44cb674bcea6599065537fdbd932948f84f61cdb95f7e2414b3b05ec14310919"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-exec_0.17.1_darwin_arm64.tar.gz"
      sha256 "322895abb814f3388d98a886e6887fa9f91c9f4ec7721786cd6befb5e82daa50"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-exec_0.17.1_linux_amd64.tar.gz"
      sha256 "161644a378785103bf9167664cfc9813631ae26a52e7530b1329c9a48e45ed16"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-exec_0.17.1_linux_arm64.tar.gz"
      sha256 "51dac80ea3a8d9c2875f3a23b88d9f7a9537cf8ba10e3c2d7408ea91248b7b39"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end
end
