# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WardgateProxy < Formula
  desc "API gateway for AI agents - local reverse proxy"
  homepage "https://github.com/wardgate/wardgate"
  version "0.18.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-proxy_0.18.0_darwin_amd64.tar.gz"
      sha256 "003706151d5544595eebb3afb87ed38e7b0c58c9600b57b3e6bd8c5a8dd1b0c7"

      define_method(:install) do
        bin.install "wardgate-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-proxy_0.18.0_darwin_arm64.tar.gz"
      sha256 "ba3a186750a39b7ddb12b4134ed7e5e8f96b37713067b7e76be019ade6a9a20a"

      define_method(:install) do
        bin.install "wardgate-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-proxy_0.18.0_linux_amd64.tar.gz"
      sha256 "18eedc485a258f9781bdbdd229a407d6f203f3912e1ee29b6176420691b511bc"
      define_method(:install) do
        bin.install "wardgate-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-proxy_0.18.0_linux_arm64.tar.gz"
      sha256 "a9b9b7cd0f321c9e568cb0fe1971e5cd3b5293a20dec43af71d9e01418b77f9b"
      define_method(:install) do
        bin.install "wardgate-proxy"
      end
    end
  end
end
