# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WardgateExec < Formula
  desc "API gateway for AI agents - conclave executor"
  homepage "https://github.com/wardgate/wardgate"
  version "0.18.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-exec_0.18.0_darwin_amd64.tar.gz"
      sha256 "5f7a816368abcca6d9b27ea4e22eda57e9c974be596dd5dc05611aa712786f4c"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-exec_0.18.0_darwin_arm64.tar.gz"
      sha256 "e770abb5ee245a0771144f8c687b9ade796af8c29f8e2cd6e4f1e3d6be43b8b4"

      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-exec_0.18.0_linux_amd64.tar.gz"
      sha256 "494316a39b214a0a80fac65fc7d1d02383012cadbea7cec6b913ac6cfc852de7"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.18.0/wardgate-exec_0.18.0_linux_arm64.tar.gz"
      sha256 "9f37b9cea4bb058f9c19c1a26e61d5ff1e55031e1ac406ae0e3e7d91fd0681cd"
      define_method(:install) do
        bin.install "wardgate-exec"
      end
    end
  end
end
