# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wardgate < Formula
  desc "API gateway for AI agents - conclave executor"
  homepage "https://github.com/wardgate/wardgate"
  version "0.13.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.13.0/wardgate-exec_0.13.0_darwin_amd64.tar.gz"
      sha256 "84f916cc359546345497bf4aea508fcd8e37d35e13b140c72529ef75eabef41e"

      def install
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.13.0/wardgate-exec_0.13.0_darwin_arm64.tar.gz"
      sha256 "5032df9ac3ce35e32968ca0bd7a95bf8ccf71227ad1be48aac8ca4eba4ecad1d"

      def install
        bin.install "wardgate-exec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.13.0/wardgate-exec_0.13.0_linux_amd64.tar.gz"
      sha256 "5937ab006cbb6f4a1c9f98c3e56c6f3698bb2445c24d030317c9a1b74bf669e3"
      def install
        bin.install "wardgate-exec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.13.0/wardgate-exec_0.13.0_linux_arm64.tar.gz"
      sha256 "94dd5d844200e31d79d679a7aae36527743d949ee4c0a01c634784904654320a"
      def install
        bin.install "wardgate-exec"
      end
    end
  end
end
