# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WardgateCli < Formula
  desc "API gateway for AI agents - CLI client"
  homepage "https://github.com/wardgate/wardgate"
  version "0.17.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-cli_0.17.1_darwin_amd64.tar.gz"
      sha256 "b8b7c9b30e5a8f807d58502ff0f160d5e8eec02c5f202a4377759828b5927ab4"

      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-cli_0.17.1_darwin_arm64.tar.gz"
      sha256 "acf594497f81bba3146f3b77220dcf8f8906e6e46b0554e67b1f6f898a45c0e7"

      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-cli_0.17.1_linux_amd64.tar.gz"
      sha256 "d34a415a5008e42018e012105663f279c4ad33df0a725a76189d7a4efeb2fb1f"
      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardgate/wardgate/releases/download/v0.17.1/wardgate-cli_0.17.1_linux_arm64.tar.gz"
      sha256 "2cfeef3e205b34ffd1a9ec5d39ff3fdf65351995b9421193dd09e9ba8acfcd0e"
      define_method(:install) do
        bin.install "wardgate-cli"
      end
    end
  end
end
